// Static concept catalogue — mirrors backend CATEGORY_SEQUENCES order
export const CONCEPT_CATEGORIES = {
  fruits: {
    key:   'fruits',
    label: 'Fruits',
    items: [
      {
        key:         'apple',
        label:       'Apple',
        labelSi:     'ඇපල්',
        icon:        require('../../assets/concepts/categories/Fruits/Fruits_Icons/apple.png'),
        real:        require('../../assets/concepts/categories/Fruits/Apple/Apple_Real.png'),
        io:          require('../../assets/concepts/categories/Fruits/Apple/Apple_IO.png'),
        animated:    require('../../assets/concepts/categories/Fruits/Apple/Apple_Animated.png'),
        introAudio:  require('../../assets/concepts/audio/Fruits/Apple/AppleIntro.m4a'),
        t1Audio:     require('../../assets/concepts/audio/Fruits/Apple/AppleT1Qestion.m4a'),
        tier3Video:  require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating apple.mp4'),
        coloring:    require('../../assets/concepts/categories/Fruits/Apple/Apple_Coloring.png'),
      },
      {
        key:        'banana',
        label:      'Bananas',
        labelSi:    'කෙසෙල්',
        plural:     true,
        icon:       require('../../assets/concepts/categories/Fruits/Fruits_Icons/banana.png'),
        real:       require('../../assets/concepts/categories/Fruits/Banana/Banana_Real.png'),
        io:         require('../../assets/concepts/categories/Fruits/Banana/Banana_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Banana/Banana_Animated.png'),
        introAudio: require('../../assets/concepts/audio/Fruits/Banana/BananaIntro.m4a'),
        t1Audio:    require('../../assets/concepts/audio/Fruits/Banana/BananaT1Question.m4a'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating banana.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Banana/Banana_Coloring.png'),
      },
      {
        key:      'cherry',
        label:    'Cherries',
        labelSi:  'චෙරි',
        plural:   true,
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/cherries.png'),
        real:     require('../../assets/concepts/categories/Fruits/Cherry/Cherry_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Cherry/Cherry_IO.jpg'),
        animated:   require('../../assets/concepts/categories/Fruits/Cherry/Cherry_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating cherry.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Cherry/Cherries_Coloring.png'),
      },
      {
        key:      'grapes',
        label:    'Grapes',
        labelSi:  'මිදි',
        plural:   true,
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/grape.png'),
        real:     require('../../assets/concepts/categories/Fruits/Grapes/Grapes_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Grapes/Grapes_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Grapes/Grapes_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating grapes.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Grapes/Grapes_Coloring.png'),
      },
      {
        key:      'guava',
        label:    'Guava',
        labelSi:  'පේර',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/guava.png'),
        real:     require('../../assets/concepts/categories/Fruits/Guava/Guava_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Guava/Guava_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Guava/Guava_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating guava.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Guava/Guava_Coloring.png'),
      },
      {
        key:      'mango',
        label:    'Mango',
        labelSi:  'අඹ',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/mango.png'),
        real:     require('../../assets/concepts/categories/Fruits/Mango/Mango_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Mango/Mango_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Mango/Mango_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating mango.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Mango/Mango_Coloring.png'),
      },
      {
        key:      'orange',
        label:    'Orange',
        labelSi:  'දොඩම්',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/orange.png'),
        real:     require('../../assets/concepts/categories/Fruits/Orange/Orange_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Orange/Orange_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Orange/Orange_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating orange.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Orange/Orange_Coloring.png'),
      },
      {
        key:      'papaya',
        label:    'Papaya',
        labelSi:  'පැපොල්',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/papaya.png'),
        real:     require('../../assets/concepts/categories/Fruits/Papaya/Papaya_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Papaya/Papaya_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Papaya/Papaya_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating papaya.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Papaya/Papaya_Coloring.png'),
      },
      {
        key:      'passion',
        label:    'Passion Fruit',
        labelSi:  'පැෂන් ෆ්‍රූට්',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/passion.png'),
        real:     require('../../assets/concepts/categories/Fruits/Passion/Passion_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Passion/Passion_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Passion/Passion_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating passion.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Passion/Passion_Coloring.png'),
      },
      {
        key:      'pineapple',
        label:    'Pineapple',
        labelSi:  'අනන්නාස්',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/pineapple.png'),
        real:     require('../../assets/concepts/categories/Fruits/Pineapple/Pineapple_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Pineapple/Pineapple_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Pineapple/Pineapple_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating pineapple.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Pineapple/Pineapple_Coloring.png'),
      },
      {
        key:      'watermelon',
        label:    'Watermelon',
        labelSi:  'කොමඩු',
        icon:     require('../../assets/concepts/categories/Fruits/Fruits_Icons/watermelon.png'),
        real:     require('../../assets/concepts/categories/Fruits/Watermelon/Watermelon_Real.png'),
        io:       require('../../assets/concepts/categories/Fruits/Watermelon/Watermelon_IO.png'),
        animated:   require('../../assets/concepts/categories/Fruits/Watermelon/Watermelon_Animated.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Fruits/Anjali eating watermelon.mp4'),
        coloring:   require('../../assets/concepts/categories/Fruits/Watermelon/Watermelon_Coloring.png'),
      },
    ],
  },
  professionals: {
    key:   'professionals',
    label: 'Professionals',
    items: [
      {
        key:      'baker',
        label:    'Baker',
        labelSi:  'බේකරය',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/baker.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/baker.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Baker/Baker_Coloring.png'),
      },
      {
        key:      'carpenter',
        label:    'Carpenter',
        labelSi:  'වඩුවා',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/carpenter.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/carpenter.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Carpenter/Carpenter_Coloring.png'),
      },
      {
        key:      'cashier',
        label:    'Cashier',
        labelSi:  'මුදල් භාරකරු',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/cashier.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/cashier.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Cashier/Cashier_Coloring.png'),
      },
      {
        key:      'doctor',
        label:    'Doctor',
        labelSi:  'වෛද්‍යවරයා',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/doctor.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/doctor.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Doctor/Doctor_Coloring.png'),
      },
      {
        key:      'farmer',
        label:    'Farmer',
        labelSi:  'ගොවියා',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/farmer.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/farmer.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Farmer/Farmer_Coloring.png'),
      },
      {
        key:      'nurse',
        label:    'Nurse',
        labelSi:  'හෙදිය',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/nurse.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/nurse.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Nurse/Nurse_Coloring.png'),
      },
      {
        key:      'principal',
        label:    'Principal',
        labelSi:  'විදුහල්පති',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/principal.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/principal.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Principal/Principal_Coloring.png'),
      },
      {
        key:      'teacher',
        label:    'Teacher',
        labelSi:  'ගුරුවරයා',
        icon:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/teacher.png'),
        real:     require('../../assets/concepts/categories/Professionals/Professionals_Icons/teacher.png'),
        coloring: require('../../assets/concepts/categories/Professionals/Teacher/Teacher_Coloring.png'),
      },
    ],
  },
  animals: {
    key:   'animals',
    label: 'Animals',
    items: [
      {
        key:        'ant',
        label:      'Ant',
        labelSi:    'කුහුඹුවා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/ant.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/ant.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Ant.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Ant/Ant_Coloring.png'),
      },
      {
        key:        'bull',
        label:      'Bull',
        labelSi:    'ගොනා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/bull.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/bull.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Bull.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Bull/Bull_Coloring.png'),
      },
      {
        key:        'butterfly',
        label:      'Butterfly',
        labelSi:    'සමනලයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/butterfly.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/butterfly.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Butterfly.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Butterfly/Butterfly_Coloring.png'),
      },
      {
        key:        'cat',
        label:      'Cat',
        labelSi:    'බළලා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/cat.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/cat.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Cat.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Cat/Cat_Coloring.png'),
      },
      {
        key:     'caterpillar',
        label:   'Caterpillar',
        labelSi: 'ගෙරි පණුවා',
        icon: require('../../assets/concepts/categories/Animals/Animals_Icons/caterpillar.png'),
        real: require('../../assets/concepts/categories/Animals/Animals_Icons/caterpillar.png'),
      },
      {
        key:        'cock',
        label:      'Cock',
        labelSi:    'කුකුළා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/Cock.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/Cock.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Cock.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Cock/Cock_Coloring.png'),
      },
      {
        key:        'cow',
        label:      'Cow',
        labelSi:    'ගවයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/cow.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/cow.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Cow.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Cow/Cow_Coloring.png'),
      },
      {
        key:        'crow',
        label:      'Crow',
        labelSi:    'කාකයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/crow.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/crow.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Crow.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Crow/Crow_Coloring.png'),
      },
      {
        key:        'dog',
        label:      'Dog',
        labelSi:    'බල්ලා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/dog.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/dog.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Dog.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Dog/Dog_Coloring.png'),
      },
      {
        key:        'elephant',
        label:      'Elephant',
        labelSi:    'අලියා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/elephant.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/elephant.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Elephant.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Elephant/Elephant_Coloring.png'),
      },
      {
        key:        'goat',
        label:      'Goat',
        labelSi:    'එළුවා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/goat.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/goat.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Goat.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Goat/Goat_Coloring.png'),
      },
      {
        key:        'hen',
        label:      'Hen',
        labelSi:    'කිකිළිය',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/hen.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/hen.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Hen.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Hen/Hen_Coloring.png'),
      },
      {
        key:        'horse',
        label:      'Horse',
        labelSi:    'අශ්වයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/horse.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/horse.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Horse.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Horse/Horse_Coloring.png'),
      },
      {
        key:        'lion',
        label:      'Lion',
        labelSi:    'සිංහයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/lion.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/lion.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Lion.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Lion/Lion_Coloring.png'),
      },
      {
        key:        'owl',
        label:      'Owl',
        labelSi:    'බාලකාවා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/owl.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/owl.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Owl.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Owl/Owl_Coloring.png'),
      },
      {
        key:        'parrot',
        label:      'Parrot',
        labelSi:    'ගිරාවා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/parrot.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/parrot.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Parrot.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Parrot/Parrot_Coloring.png'),
      },
      {
        key:        'peacock',
        label:      'Peacock',
        labelSi:    'මොණරා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/peacock.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/peacock.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Peacock.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Peacock/Peacock_Coloring.png'),
      },
      {
        key:        'rabbit',
        label:      'Rabbit',
        labelSi:    'හාවා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/rabbit.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/rabbit.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Rabbit.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Rabbit/Rabbit_Coloring.png'),
      },
      {
        key:        'snake',
        label:      'Snake',
        labelSi:    'සර්පයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/snake.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/snake.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Snake.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Snake/Snake_Coloring.png'),
      },
      {
        key:        'sparrow',
        label:      'Sparrow',
        labelSi:    'ඇහැළිය',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/sparrow.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/sparrow.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Sparrow.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Sparrow/Sparrow_Coloring.png'),
      },
      {
        key:        'tiger',
        label:      'Tiger',
        labelSi:    'ව්‍යාඝ්‍රයා',
        icon:       require('../../assets/concepts/categories/Animals/Animals_Icons/tiger.png'),
        real:       require('../../assets/concepts/categories/Animals/Animals_Icons/tiger.png'),
        tier3Video: require('../../assets/concepts/Tier3_videos/Animals/Tiger.mp4'),
        coloring:   require('../../assets/concepts/categories/Animals/Tiger/Toger_Coloring.png'),
      },
    ],
  },
  house: {
    key:   'house',
    label: 'House Parts',
    items: [
      {
        key:     'door',
        label:   'Door',
        labelSi: 'දොර',
        icon: require('../../assets/concepts/categories/House Parts/House_Icons/door.png'),
        real: require('../../assets/concepts/categories/House Parts/House_Icons/door.png'),
      },
      {
        key:     'roof',
        label:   'Roof',
        labelSi: 'වහල',
        icon: require('../../assets/concepts/categories/House Parts/House_Icons/roof.png'),
        real: require('../../assets/concepts/categories/House Parts/House_Icons/roof.png'),
      },
      {
        key:     'wall',
        label:   'Wall',
        labelSi: 'බිත්තිය',
        icon: require('../../assets/concepts/categories/House Parts/House_Icons/wall.png'),
        real: require('../../assets/concepts/categories/House Parts/House_Icons/wall.png'),
      },
      {
        key:     'windows',
        label:   'Windows',
        labelSi: 'ජනේල',
        plural:  true,
        icon: require('../../assets/concepts/categories/House Parts/House_Icons/windows.png'),
        real: require('../../assets/concepts/categories/House Parts/House_Icons/windows.png'),
      },
    ],
  },
  numbers: {
    key:   'numbers',
    label: 'Numbers',
    items: [
      {
        key:     'one',
        label:   'One',
        labelSi: 'එක',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/one.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/one.png'),
      },
      {
        key:     'two',
        label:   'Two',
        labelSi: 'දෙක',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/two.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/two.png'),
      },
      {
        key:     'three',
        label:   'Three',
        labelSi: 'තුන',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/three.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/three.png'),
      },
      {
        key:     'four',
        label:   'Four',
        labelSi: 'හතර',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/four.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/four.png'),
      },
      {
        key:     'five',
        label:   'Five',
        labelSi: 'පහ',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/five.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/five.png'),
      },
      {
        key:     'six',
        label:   'Six',
        labelSi: 'හය',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/six.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/six.png'),
      },
      {
        key:     'seven',
        label:   'Seven',
        labelSi: 'හත',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/seven.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/seven.png'),
      },
      {
        key:     'eight',
        label:   'Eight',
        labelSi: 'අට',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/eight.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/eight.png'),
      },
      {
        key:     'nine',
        label:   'Nine',
        labelSi: 'නවය',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/nine.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/nine.png'),
      },
      {
        key:     'ten',
        label:   'Ten',
        labelSi: 'දහය',
        icon: require('../../assets/concepts/categories/Numbers/Numbers_Icons/ten.png'),
        real: require('../../assets/concepts/categories/Numbers/Numbers_Icons/ten.png'),
      },
    ],
  },
  shapes: {
    key:   'shapes',
    label: 'Shapes',
    items: [
      {
        key:     'circle',
        label:   'Circle',
        labelSi: 'කවය',
        icon: require('../../assets/concepts/categories/Shapes/Shapes_Icons/circle.png'),
        real: require('../../assets/concepts/categories/Shapes/Shapes_Icons/circle.png'),
      },
      {
        key:     'square',
        label:   'Square',
        labelSi: 'චතුරශ්‍රය',
        icon: require('../../assets/concepts/categories/Shapes/Shapes_Icons/square.png'),
        real: require('../../assets/concepts/categories/Shapes/Shapes_Icons/square.png'),
      },
      {
        key:     'rectangle',
        label:   'Rectangle',
        labelSi: 'සෘජුකෝණාස්‍රය',
        icon: require('../../assets/concepts/categories/Shapes/Shapes_Icons/rectangle.png'),
        real: require('../../assets/concepts/categories/Shapes/Shapes_Icons/rectangle.png'),
      },
      {
        key:     'triangle',
        label:   'Triangle',
        labelSi: 'ත්‍රිකෝණය',
        icon: require('../../assets/concepts/categories/Shapes/Shapes_Icons/triangle.png'),
        real: require('../../assets/concepts/categories/Shapes/Shapes_Icons/triangle.png'),
      },
    ],
  },
  colors: {
    key:   'colors',
    label: 'Colours',
    items: [
      {
        key:   'red',
        label: 'Red',
        labelSi: 'රතු',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/red.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/red.png'),
      },
      {
        key:   'blue',
        label: 'Blue',
        labelSi: 'නිල්',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/blue.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/blue.png'),
      },
      {
        key:   'green',
        label: 'Green',
        labelSi: 'කොළ',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/green.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/green.png'),
      },
      {
        key:   'yellow',
        label: 'Yellow',
        labelSi: 'කහ',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/yellow.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/yellow.png'),
      },
      {
        key:   'orange',
        label: 'Orange',
        labelSi: 'තැඹිලි',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/orange.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/orange.png'),
      },
      {
        key:   'pink',
        label: 'Pink',
        labelSi: 'රෝස',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/pink.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/pink.png'),
      },
      {
        key:   'purple',
        label: 'Purple',
        labelSi: 'දම්',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/purple.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/purple.png'),
      },
      {
        key:   'brown',
        label: 'Brown',
        labelSi: 'දුඹුරු',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/brown.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/brown.png'),
      },
      {
        key:   'black',
        label: 'Black',
        labelSi: 'කළු',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/black.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/black.png'),
      },
      {
        key:   'white',
        label: 'White',
        labelSi: 'සුදු',
        icon: require('../../assets/concepts/categories/Colors/Colors_Icons/white.png'),
        real: require('../../assets/concepts/categories/Colors/Colors_Icons/white.png'),
      },
    ],
  },
  household: {
    key:   'household',
    label: 'Household Items',
    items: [
      {
        key:      'bed',
        label:    'Bed',
        labelSi:  'ඇඳ',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/bed.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/bed.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Bed/Bed_Coloring.png'),
      },
      {
        key:      'brush',
        label:    'Brush',
        labelSi:  'බ්‍රෂය',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/brush.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/brush.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Brush/Brush_Coloring.png'),
      },
      {
        key:      'comb',
        label:    'Comb',
        labelSi:  'කෙස් තෙලියා',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/comb.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/comb.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Comb/Comb_Coloring.png'),
      },
      {
        key:      'cup',
        label:    'Cup',
        labelSi:  'කෝප්පය',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/cup.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/cup.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Cup/Cup_Coloring.png'),
      },
      {
        key:      'fork',
        label:    'Fork',
        labelSi:  'ගෑරප්පුව',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/fork.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/fork.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Fork/Fork_Coloring.png'),
      },
      {
        key:      'glass',
        label:    'Glass',
        labelSi:  'වීදුරුව',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/glass.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/glass.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Glass/Glass_Coloring.png'),
      },
      {
        key:      'knife',
        label:    'Knife',
        labelSi:  'පිහිය',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/knife.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/knife.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Knife/Knife_Coloring.png'),
      },
      {
        key:      'mug',
        label:    'Mug',
        labelSi:  'මගය',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/mug.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/mug.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Mug/Mug_Coloring.png'),
      },
      {
        key:      'pillows',
        label:    'Pillows',
        labelSi:  'කොට්ට',
        plural:   true,
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/pillows.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/pillows.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Pillow/Pillows_Coloring.png'),
      },
      {
        key:      'plate',
        label:    'Plate',
        labelSi:  'තැටිය',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/plate.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/plate.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Plate/Plate_Coloring.png'),
      },
      {
        key:      'soap',
        label:    'Soap',
        labelSi:  'සබන්',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/soap.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/soap.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Soap/Soap_Coloring.png'),
      },
      {
        key:      'spoon',
        label:    'Spoon',
        labelSi:  'හැන්ද',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/spoon.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/spoon.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Spoon/Spoon_Coloring.png'),
      },
      {
        key:      'toothbrush',
        label:    'Toothbrush',
        labelSi:  'දත් බ්‍රෂය',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/toothbrush.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/toothbrush.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Toothbrush/Toothbrush_Coloring.png'),
      },
      {
        key:      'toothpaste',
        label:    'Toothpaste',
        labelSi:  'දත් කිරිල්ල',
        icon:     require('../../assets/concepts/categories/Household Items/Household_Icons/toothpaste.png'),
        real:     require('../../assets/concepts/categories/Household Items/Household_Icons/toothpaste.png'),
        coloring: require('../../assets/concepts/categories/Household Items/Toothpaste/Toothpaste_Coloring.png'),
      },
    ],
  },
  classroom: {
    key:   'classroom',
    label: 'Classroom Objects',
    items: [
      {
        key:      'bag',
        label:    'Bag',
        labelSi:  'බෑගය',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/bag.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Bag/Bag_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Bag/Bag_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Bag/Bag_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Bag/Bag_Coloring.png'),
      },
      {
        key:      'blackboard',
        label:    'Blackboard',
        labelSi:  'කළු පුවරුව',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/blackboard.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Blackboard/Blackboard_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Blackboard/Blackboard_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Blackboard/Blackboard_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Blackboard/Blackboard_Coloring.png'),
      },
      {
        key:      'book',
        label:    'Book',
        labelSi:  'පොත',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/book.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Book/Book_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Book/Book_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Book/Book_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Book/Book_Coloring.png'),
      },
      {
        key:      'bottle',
        label:    'Bottle',
        labelSi:  'බෝතලය',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/bottle.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Bottle/Bottle_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Bottle/Bottle_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Bottle/Bottle_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Bottle/Bottle_Coloring.png'),
      },
      {
        key:      'chair',
        label:    'Chair',
        labelSi:  'පුටුව',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/chair.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Chair/Chair_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Chair/Chair__Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Chair/Chair_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Chair/Chair__Coloring.png'),
      },
      {
        key:      'desk',
        label:    'Desk',
        labelSi:  'ඩෙස්කය',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/desk.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Desk/Desk_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Desk/Desk_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Desk/Desk_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Desk/Desk_Coloring.png'),
      },
      {
        key:      'dustbin',
        label:    'Dustbin',
        labelSi:  'කුණු බකට',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/dustbin.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Dustbin/Dustbin_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Dustbin/Dustbin_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Dustbin/Dustbin_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Dustbin/Dustbin_Coloring.png'),
      },
      {
        key:      'eraser',
        label:    'Eraser',
        labelSi:  'ඉරේසරය',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/eraser.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Eraser/Eraser_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Eraser/Eraser_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Eraser/Eraser_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Eraser/Eraser_Coloring.png'),
      },
      {
        key:      'pencil',
        label:    'Pencil',
        labelSi:  'පැන්සල',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/pencil.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Pencil/Pencil_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Pencil/Pencil_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Pencil/Pencil_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Pencil/Pencil_Coloring.png'),
      },
      {
        key:      'ruler',
        label:    'Ruler',
        labelSi:  'රූලරය',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/ruler.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Ruler/Ruler_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Ruler/Ruler_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Ruler/Ruler_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Ruler/Ruler_Coloring.png'),
      },
      {
        key:      'table',
        label:    'Table',
        labelSi:  'මේසය',
        icon:     require('../../assets/concepts/categories/Classroom Objects/Classroom_Icons/table.png'),
        real:     require('../../assets/concepts/categories/Classroom Objects/Table/Table_Real.png'),
        io:       require('../../assets/concepts/categories/Classroom Objects/Table/Table_Coloring.png'),
        animated: require('../../assets/concepts/categories/Classroom Objects/Table/Table_Animated.png'),
        coloring: require('../../assets/concepts/categories/Classroom Objects/Table/Table_Coloring.png'),
      },
    ],
  },
};

const VOWELS = new Set(['a', 'e', 'i', 'o', 'u']);

export function getConceptPhrase(concept) {
  if (!concept) return '';
  if (concept.plural) return `These are ${concept.label}`;
  const article = VOWELS.has(concept.label[0].toLowerCase()) ? 'an' : 'a';
  return `This is ${article} ${concept.label}`;
}

export function getConceptQuestion(concept) {
  if (!concept) return '';
  if (concept.plural) return `Can you find ${concept.label} here?`;
  const article = VOWELS.has(concept.label[0].toLowerCase()) ? 'an' : 'a';
  return `Can you find ${article} ${concept.label} here?`;
}

// Sinhala has no articles — structure is the same for singular and plural
export function getConceptQuestionSi(concept) {
  if (!concept?.labelSi) return '';
  return `ඔයාට ${concept.labelSi} හොයාගන්න පුළුවන්ද?`;
}

export function getConceptItem(categoryKey, conceptKey) {
  const cat = CONCEPT_CATEGORIES[categoryKey];
  if (!cat) return null;
  return cat.items.find((it) => it.key === conceptKey) || null;
}

export function getConceptItemsForCategory(categoryKey) {
  return CONCEPT_CATEGORIES[categoryKey]?.items ?? [];
}
