export const WORD_AUDIO_ASSETS = {
  ant: require("../../../../assets/pronunciation-audios/ant.mp3"),
  bird: require("../../../../assets/pronunciation-audios/bird.mp3"),
  buffalo: require("../../../../assets/pronunciation-audios/buffalo.mp3"),
  butterfly: require("../../../../assets/pronunciation-audios/butterfly.mp3"),
  cat: require("../../../../assets/pronunciation-audios/cat.mp3"),
  chick: require("../../../../assets/pronunciation-audios/chick.mp3"),
  cow: require("../../../../assets/pronunciation-audios/cow.mp3"),
  crab: require("../../../../assets/pronunciation-audios/crab.mp3"),
  deer: require("../../../../assets/pronunciation-audios/deer.mp3"),
  dog: require("../../../../assets/pronunciation-audios/dog.mp3"),
  eagle: require("../../../../assets/pronunciation-audios/eagle.mp3"),
  elephant: require("../../../../assets/pronunciation-audios/elephant.mp3"),
  fish: require("../../../../assets/pronunciation-audios/fish.mp3"),
  fox: require("../../../../assets/pronunciation-audios/fox.mp3"),
  goose: require("../../../../assets/pronunciation-audios/goose.mp3"),
  hippo: require("../../../../assets/pronunciation-audios/hippo.mp3"),
  horse: require("../../../../assets/pronunciation-audios/horse.mp3"),
  jellyfish: require("../../../../assets/pronunciation-audios/jellyfish.mp3"),
  kangaroo: require("../../../../assets/pronunciation-audios/kangaroo.mp3"),
  leopard: require("../../../../assets/pronunciation-audios/leopard.mp3"),
  mosquito: require("../../../../assets/pronunciation-audios/mosquito.mp3"),
  penguin: require("../../../../assets/pronunciation-audios/penguin.mp3"),
  pigeon: require("../../../../assets/pronunciation-audios/pigeon.mp3"),
  snail: require("../../../../assets/pronunciation-audios/snail.mp3"),
  tiger: require("../../../../assets/pronunciation-audios/tiger.mp3"),
  turtle: require("../../../../assets/pronunciation-audios/turtle.mp3"),
  whale: require("../../../../assets/pronunciation-audios/whale.mp3"),
  worm: require("../../../../assets/pronunciation-audios/worm.mp3"),

  // Classroom
  bag: require("../../../../assets/pronunciation-audios/bag.mp3"),
  book: require("../../../../assets/pronunciation-audios/book.mp3"),
  chair: require("../../../../assets/pronunciation-audios/chair.mp3"),
  desk: require("../../../../assets/pronunciation-audios/desk.mp3"),
  door: require("../../../../assets/pronunciation-audios/door.mp3"),
  pen: require("../../../../assets/pronunciation-audios/pen.mp3"),
  pencil: require("../../../../assets/pronunciation-audios/pencil.mp3"),
  ruler: require("../../../../assets/pronunciation-audios/ruler.mp3"),

  // Fruits
  apple: require("../../../../assets/pronunciation-audios/apple.mp3"),
  banana: require("../../../../assets/pronunciation-audios/banana.mp3"),
  grape: require("../../../../assets/pronunciation-audios/grape.mp3"),
  guava: require("../../../../assets/pronunciation-audios/guava.mp3"),
  lemon: require("../../../../assets/pronunciation-audios/lemon.mp3"),
  mango: require("../../../../assets/pronunciation-audios/mango.mp3"),
  orange: require("../../../../assets/pronunciation-audios/orange.mp3"),
  papaya: require("../../../../assets/pronunciation-audios/papaya.mp3"),

  // Daily Actions
  clap: require("../../../../assets/pronunciation-audios/clap.mp3"),
  drink: require("../../../../assets/pronunciation-audios/drink.mp3"),
  eat: require("../../../../assets/pronunciation-audios/eat.mp3"),
  jump: require("../../../../assets/pronunciation-audios/jump.mp3"),
  read: require("../../../../assets/pronunciation-audios/read.mp3"),
  run: require("../../../../assets/pronunciation-audios/run.mp3"),
  sleep: require("../../../../assets/pronunciation-audios/sleep.mp3"),
  walk: require("../../../../assets/pronunciation-audios/walk.mp3"),

  // Alphabet (letter names, e.g. "b" -> "bee"). The alphabet mode looks its
  // clips up in this same map by letter id, so without these entries every
  // letter falls through to the "Audio unavailable" branch and the whole mode
  // is silent.
  a: require("../../../../assets/pronunciation-audios/a.mp3"),
  b: require("../../../../assets/pronunciation-audios/b.mp3"),
  c: require("../../../../assets/pronunciation-audios/c.mp3"),
  d: require("../../../../assets/pronunciation-audios/d.mp3"),
  e: require("../../../../assets/pronunciation-audios/e.mp3"),
  f: require("../../../../assets/pronunciation-audios/f.mp3"),
  g: require("../../../../assets/pronunciation-audios/g.mp3"),
  h: require("../../../../assets/pronunciation-audios/h.mp3"),
  i: require("../../../../assets/pronunciation-audios/i.mp3"),
  j: require("../../../../assets/pronunciation-audios/j.mp3"),
  k: require("../../../../assets/pronunciation-audios/k.mp3"),
  l: require("../../../../assets/pronunciation-audios/l.mp3"),
  m: require("../../../../assets/pronunciation-audios/m.mp3"),
  n: require("../../../../assets/pronunciation-audios/n.mp3"),
  o: require("../../../../assets/pronunciation-audios/o.mp3"),
  p: require("../../../../assets/pronunciation-audios/p.mp3"),
  q: require("../../../../assets/pronunciation-audios/q.mp3"),
  r: require("../../../../assets/pronunciation-audios/r.mp3"),
  s: require("../../../../assets/pronunciation-audios/s.mp3"),
  t: require("../../../../assets/pronunciation-audios/t.mp3"),
  u: require("../../../../assets/pronunciation-audios/u.mp3"),
  v: require("../../../../assets/pronunciation-audios/v.mp3"),
  w: require("../../../../assets/pronunciation-audios/w.mp3"),
  x: require("../../../../assets/pronunciation-audios/x.mp3"),
  y: require("../../../../assets/pronunciation-audios/y.mp3"),
  z: require("../../../../assets/pronunciation-audios/z.mp3"),
};

export const WORD_AUDIO_IDS = Object.keys(WORD_AUDIO_ASSETS);
