export const WORD_AUDIO_ASSETS = {
  ant: require("../../../../../../assets/pronounciation-audios/ant.mp3"),
  bird: require("../../../../../../assets/pronounciation-audios/bird.mp3"),
  buffalo: require("../../../../../../assets/pronounciation-audios/buffalo.mp3"),
  butterfly: require("../../../../../../assets/pronounciation-audios/butterfly.mp3"),
  cat: require("../../../../../../assets/pronounciation-audios/cat.mp3"),
  chick: require("../../../../../../assets/pronounciation-audios/chick.mp3"),
  cow: require("../../../../../../assets/pronounciation-audios/cow.mp3"),
  crab: require("../../../../../../assets/pronounciation-audios/crab.mp3"),
  deer: require("../../../../../../assets/pronounciation-audios/deer.mp3"),
  dog: require("../../../../../../assets/pronounciation-audios/dog.mp3"),
  eagle: require("../../../../../../assets/pronounciation-audios/eagle.mp3"),
  elephant: require("../../../../../../assets/pronounciation-audios/elephant.mp3"),
  fish: require("../../../../../../assets/pronounciation-audios/fish.mp3"),
  fox: require("../../../../../../assets/pronounciation-audios/fox.mp3"),
  goose: require("../../../../../../assets/pronounciation-audios/goose.mp3"),
  hippo: require("../../../../../../assets/pronounciation-audios/hippo.mp3"),
  horse: require("../../../../../../assets/pronounciation-audios/horse.mp3"),
  jellyfish: require("../../../../../../assets/pronounciation-audios/jellyfish.mp3"),
  kangaroo: require("../../../../../../assets/pronounciation-audios/kangaroo.mp3"),
  leopard: require("../../../../../../assets/pronounciation-audios/leopard.mp3"),
  mosquito: require("../../../../../../assets/pronounciation-audios/mosquito.mp3"),
  penguin: require("../../../../../../assets/pronounciation-audios/penguin.mp3"),
  pigeon: require("../../../../../../assets/pronounciation-audios/pigeon.mp3"),
  snail: require("../../../../../../assets/pronounciation-audios/snail.mp3"),
  tiger: require("../../../../../../assets/pronounciation-audios/tiger.mp3"),
  turtle: require("../../../../../../assets/pronounciation-audios/turtle.mp3"),
  whale: require("../../../../../../assets/pronounciation-audios/whale.mp3"),
  worm: require("../../../../../../assets/pronounciation-audios/worm.mp3"),

  // Classroom
  bag: require("../../../../../../assets/pronounciation-audios/bag.mp3"),
  book: require("../../../../../../assets/pronounciation-audios/book.mp3"),
  chair: require("../../../../../../assets/pronounciation-audios/chair.mp3"),
  desk: require("../../../../../../assets/pronounciation-audios/desk.mp3"),
  door: require("../../../../../../assets/pronounciation-audios/door.mp3"),
  pen: require("../../../../../../assets/pronounciation-audios/pen.mp3"),
  pencil: require("../../../../../../assets/pronounciation-audios/pencil.mp3"),
  ruler: require("../../../../../../assets/pronounciation-audios/ruler.mp3"),

  // Fruits
  apple: require("../../../../../../assets/pronounciation-audios/apple.mp3"),
  banana: require("../../../../../../assets/pronounciation-audios/banana.mp3"),
  grape: require("../../../../../../assets/pronounciation-audios/grape.mp3"),
  guava: require("../../../../../../assets/pronounciation-audios/guava.mp3"),
  lemon: require("../../../../../../assets/pronounciation-audios/lemon.mp3"),
  mango: require("../../../../../../assets/pronounciation-audios/mango.mp3"),
  orange: require("../../../../../../assets/pronounciation-audios/orange.mp3"),
  papaya: require("../../../../../../assets/pronounciation-audios/papaya.mp3"),

  // Daily Actions
  clap: require("../../../../../../assets/pronounciation-audios/clap.mp3"),
  drink: require("../../../../../../assets/pronounciation-audios/drink.mp3"),
  eat: require("../../../../../../assets/pronounciation-audios/eat.mp3"),
  jump: require("../../../../../../assets/pronounciation-audios/jump.mp3"),
  read: require("../../../../../../assets/pronounciation-audios/read.mp3"),
  run: require("../../../../../../assets/pronounciation-audios/run.mp3"),
  sleep: require("../../../../../../assets/pronounciation-audios/sleep.mp3"),
  walk: require("../../../../../../assets/pronounciation-audios/walk.mp3"),

  // Alphabet (letter names, e.g. "b" -> "bee")
  a: require("../../../../../../assets/pronounciation-audios/a.mp3"),
  b: require("../../../../../../assets/pronounciation-audios/b.mp3"),
  c: require("../../../../../../assets/pronounciation-audios/c.mp3"),
  d: require("../../../../../../assets/pronounciation-audios/d.mp3"),
  e: require("../../../../../../assets/pronounciation-audios/e.mp3"),
  f: require("../../../../../../assets/pronounciation-audios/f.mp3"),
  g: require("../../../../../../assets/pronounciation-audios/g.mp3"),
  h: require("../../../../../../assets/pronounciation-audios/h.mp3"),
  i: require("../../../../../../assets/pronounciation-audios/i.mp3"),
  j: require("../../../../../../assets/pronounciation-audios/j.mp3"),
  k: require("../../../../../../assets/pronounciation-audios/k.mp3"),
  l: require("../../../../../../assets/pronounciation-audios/l.mp3"),
  m: require("../../../../../../assets/pronounciation-audios/m.mp3"),
  n: require("../../../../../../assets/pronounciation-audios/n.mp3"),
  o: require("../../../../../../assets/pronounciation-audios/o.mp3"),
  p: require("../../../../../../assets/pronounciation-audios/p.mp3"),
  q: require("../../../../../../assets/pronounciation-audios/q.mp3"),
  r: require("../../../../../../assets/pronounciation-audios/r.mp3"),
  s: require("../../../../../../assets/pronounciation-audios/s.mp3"),
  t: require("../../../../../../assets/pronounciation-audios/t.mp3"),
  u: require("../../../../../../assets/pronounciation-audios/u.mp3"),
  v: require("../../../../../../assets/pronounciation-audios/v.mp3"),
  w: require("../../../../../../assets/pronounciation-audios/w.mp3"),
  x: require("../../../../../../assets/pronounciation-audios/x.mp3"),
  y: require("../../../../../../assets/pronounciation-audios/y.mp3"),
  z: require("../../../../../../assets/pronounciation-audios/z.mp3"),
};

export const WORD_AUDIO_IDS = Object.keys(WORD_AUDIO_ASSETS);
