export const WORD_BANK = {
  animals: [
    {
      id: "cat",
      word: "cat",
      color: "#9AD8C0",
      phonemeCount: 5,
      sounds: [
        { text: "k", type: "consonant" },
        { text: "æ", type: "vowel" },
        { text: "t", type: "consonant" },
      ],
      imageUri:
        "https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "dog",
      word: "dog",
      color: "#F4C11A",
      phonemeCount: 5,
      sounds: [
        { text: "d", type: "consonant" },
        { text: "ɒ", type: "vowel" },
        { text: "g", type: "consonant" },
      ],
      imageUri:
        "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "fish",
      word: "fish",
      color: "#2A4BD8",
      phonemeCount: 5,
      sounds: [
        { text: "f", type: "consonant" },
        { text: "ɪ", type: "vowel" },
        { text: "ʃ", type: "consonant" },
      ],
      imageUri:
        "https://images.unsplash.com/photo-1520302514739-ff49ca9db8c6?auto=format&fit=crop&w=900&q=80",
    },
    {
      id: "bird",
      word: "bird",
      color: "#E5E9EF",
      phonemeCount: 5,
      sounds: [
        { text: "b", type: "consonant" },
        { text: "ɜː", type: "vowel" },
        { text: "d", type: "consonant" },
      ],
      imageUri: null,
    },
  ],
  moreAnimals: [
    {
      id: "worm",
      word: "worm",
      color: "#D8E8C7",
      phonemeCount: 4,
      sounds: [
        { text: "w", type: "consonant" },
        { text: "ɜː", type: "vowel" },
        { text: "m", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "whale",
      word: "whale",
      color: "#DDEBFA",
      phonemeCount: 5,
      sounds: [
        { text: "w", type: "consonant" },
        { text: "eɪ", type: "vowel" },
        { text: "l", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "turtle",
      word: "turtle",
      color: "#D8EFD7",
      phonemeCount: 6,
      sounds: [
        { text: "t", type: "consonant" },
        { text: "ɜː", type: "vowel" },
        { text: "t", type: "consonant" },
        { text: "əl", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "tiger",
      word: "tiger",
      color: "#F7D8B9",
      phonemeCount: 5,
      sounds: [
        { text: "t", type: "consonant" },
        { text: "aɪ", type: "vowel" },
        { text: "gə", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "snail",
      word: "snail",
      color: "#E9E2D8",
      phonemeCount: 5,
      sounds: [
        { text: "s", type: "consonant" },
        { text: "n", type: "consonant" },
        { text: "eɪ", type: "vowel" },
        { text: "l", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "pigeon",
      word: "pigeon",
      color: "#E0E7EF",
      phonemeCount: 6,
      sounds: [
        { text: "p", type: "consonant" },
        { text: "ɪ", type: "vowel" },
        { text: "dʒ", type: "consonant" },
        { text: "ən", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "penguin",
      word: "penguin",
      color: "#DDE6F5",
      phonemeCount: 7,
      sounds: [
        { text: "p", type: "consonant" },
        { text: "e", type: "vowel" },
        { text: "ŋ", type: "consonant" },
        { text: "gwɪn", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "mosquito",
      word: "mosquito",
      color: "#F8E4B8",
      phonemeCount: 8,
      sounds: [
        { text: "m", type: "consonant" },
        { text: "ɒ", type: "vowel" },
        { text: "sk", type: "consonant" },
        { text: "iː", type: "vowel" },
        { text: "təʊ", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "leopard",
      word: "leopard",
      color: "#F3D6A1",
      phonemeCount: 7,
      sounds: [
        { text: "l", type: "consonant" },
        { text: "e", type: "vowel" },
        { text: "p", type: "consonant" },
        { text: "əd", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "kangaroo",
      word: "kangaroo",
      color: "#EAD8C6",
      phonemeCount: 8,
      sounds: [
        { text: "k", type: "consonant" },
        { text: "æ", type: "vowel" },
        { text: "ŋg", type: "consonant" },
        { text: "ə", type: "vowel" },
        { text: "ruː", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "jellyfish",
      word: "jellyfish",
      color: "#DCEFFE",
      phonemeCount: 9,
      sounds: [
        { text: "dʒ", type: "consonant" },
        { text: "e", type: "vowel" },
        { text: "l", type: "consonant" },
        { text: "i", type: "vowel" },
        { text: "f", type: "consonant" },
        { text: "ɪʃ", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "horse",
      word: "horse",
      color: "#E7E1D7",
      phonemeCount: 5,
      sounds: [
        { text: "h", type: "consonant" },
        { text: "ɔː", type: "vowel" },
        { text: "s", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "hippo",
      word: "hippo",
      color: "#DDE6EE",
      phonemeCount: 5,
      sounds: [
        { text: "h", type: "consonant" },
        { text: "ɪ", type: "vowel" },
        { text: "p", type: "consonant" },
        { text: "əʊ", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "goose",
      word: "goose",
      color: "#E7F1D9",
      phonemeCount: 5,
      sounds: [
        { text: "g", type: "consonant" },
        { text: "uː", type: "vowel" },
        { text: "s", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "fox",
      word: "fox",
      color: "#F7D7C5",
      phonemeCount: 3,
      sounds: [
        { text: "f", type: "consonant" },
        { text: "ɒ", type: "vowel" },
        { text: "ks", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "elephant",
      word: "elephant",
      color: "#E4E4E4",
      phonemeCount: 8,
      sounds: [
        { text: "e", type: "vowel" },
        { text: "l", type: "consonant" },
        { text: "ə", type: "vowel" },
        { text: "f", type: "consonant" },
        { text: "ənt", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "eagle",
      word: "eagle",
      color: "#DDE4F2",
      phonemeCount: 5,
      sounds: [
        { text: "iː", type: "vowel" },
        { text: "g", type: "consonant" },
        { text: "əl", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "deer",
      word: "deer",
      color: "#E7EFE0",
      phonemeCount: 4,
      sounds: [
        { text: "d", type: "consonant" },
        { text: "ɪə", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "crab",
      word: "crab",
      color: "#F8E0DA",
      phonemeCount: 4,
      sounds: [
        { text: "k", type: "consonant" },
        { text: "r", type: "consonant" },
        { text: "æ", type: "vowel" },
        { text: "b", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "cow",
      word: "cow",
      color: "#F4EFD8",
      phonemeCount: 3,
      sounds: [
        { text: "k", type: "consonant" },
        { text: "aʊ", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "chick",
      word: "chick",
      color: "#F8F0C9",
      phonemeCount: 5,
      sounds: [
        { text: "tʃ", type: "consonant" },
        { text: "ɪ", type: "vowel" },
        { text: "k", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "butterfly",
      word: "butterfly",
      color: "#E7DFF8",
      phonemeCount: 9,
      sounds: [
        { text: "b", type: "consonant" },
        { text: "ʌ", type: "vowel" },
        { text: "t", type: "consonant" },
        { text: "ə", type: "vowel" },
        { text: "flaɪ", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "buffalo",
      word: "buffalo",
      color: "#E6D7C1",
      phonemeCount: 7,
      sounds: [
        { text: "b", type: "consonant" },
        { text: "ʌ", type: "vowel" },
        { text: "f", type: "consonant" },
        { text: "ə", type: "vowel" },
        { text: "ləʊ", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "ant",
      word: "ant",
      color: "#E0E8D7",
      phonemeCount: 3,
      sounds: [
        { text: "æ", type: "vowel" },
        { text: "n", type: "consonant" },
        { text: "t", type: "consonant" },
      ],
      imageUri: null,
    },
  ],
  classroom: [
    {
      id: "book",
      word: "book",
      color: "#DFF3E2",
      phonemeCount: 4,
      sounds: [
        { text: "b", type: "consonant" },
        { text: "ʊ", type: "vowel" },
        { text: "k", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "desk",
      word: "desk",
      color: "#E8F2FF",
      phonemeCount: 4,
      sounds: [
        { text: "d", type: "consonant" },
        { text: "e", type: "vowel" },
        { text: "sk", type: "consonant" },
      ],
      imageUri: null,
    },
  ],
  fruits: [
    {
      id: "apple",
      word: "apple",
      color: "#FCEFCF",
      phonemeCount: 5,
      sounds: [
        { text: "a", type: "vowel" },
        { text: "p", type: "consonant" },
        { text: "əl", type: "vowel" },
      ],
      imageUri: null,
    },
    {
      id: "mango",
      word: "mango",
      color: "#FFE4B8",
      phonemeCount: 5,
      sounds: [
        { text: "m", type: "consonant" },
        { text: "æ", type: "vowel" },
        { text: "ŋgəʊ", type: "consonant" },
      ],
      imageUri: null,
    },
  ],
  "daily-actions": [
    {
      id: "walk",
      word: "walk",
      color: "#FDE3DF",
      phonemeCount: 4,
      sounds: [
        { text: "w", type: "consonant" },
        { text: "ɔː", type: "vowel" },
        { text: "k", type: "consonant" },
      ],
      imageUri: null,
    },
    {
      id: "jump",
      word: "jump",
      color: "#F8D9D4",
      phonemeCount: 4,
      sounds: [
        { text: "dʒ", type: "consonant" },
        { text: "ʌ", type: "vowel" },
        { text: "mp", type: "consonant" },
      ],
      imageUri: null,
    },
  ],
};
