/**
 * masteredLetterFiltering.js
 *
 * Feature 11B Phase 5 §2/§3/§4/§5 — fixes the normal-learning progression
 * bug the earlier audit proved: mastered letters were never skipped, so
 * every new session restarted the full adaptive sequence from letter #1.
 * This is a normal-progression fix, NOT a Feature 11B adaptation change
 * (spec §21) — Feature 11B remains read-only.
 *
 * Two pieces, matching this project's established "thin impure fetch
 * wrapper + pure normalization/logic, never throws" contract (see
 * initialAssessmentShapes.js, motorBaseline.js):
 *   - fetchMasteredLetters()      — GET /handwriting/mastered-letters/:id,
 *     the SAME backend LetterProgress source of truth the audit confirmed
 *     is authoritative (spec §3 — frontend AsyncStorage completed flags
 *     are never used here).
 *   - filterUnmasteredSequence()  — pure function: removes already-
 *     mastered (letter, caseType) pairs from a sequence array WITHOUT
 *     reordering the remaining entries (spec §4: "Do NOT destroy the
 *     original adaptive order. Filtering should preserve the order
 *     generated by adaptiveSequencing").
 *
 * No positional cursor (letterIdx) is ever persisted across sessions
 * (spec §5) — filtering the full stored sequence against authoritative
 * mastery, every time a writing screen mounts, naturally reconstructs
 * "start from the first remaining unmastered item." A child who mastered
 * l and i but not t, in a sequence [l, i, t, o, c, ...], gets an effective
 * sequence of [t, o, c, ...] on every subsequent visit — regardless of
 * which day, app restart, or device.
 */

'use strict';

import client from '../api/client';
import { ENDPOINTS } from '../constants/api';

const FAILSAFE = Object.freeze({ status: 'read_failed', pairs: [] });

function pairKey(letter, caseType) {
  return `${letter}|${caseType}`;
}

/**
 * @param {*} data — response.data, or undefined/null.
 * @returns {{status: 'found'|'read_failed', pairs: Array<{letter: string, caseType: string}>}}
 */
export function normalizeMasteredLettersResponse(data) {
  if (!data || typeof data !== 'object' || data.status !== 'found' || !Array.isArray(data.pairs)) {
    return { ...FAILSAFE };
  }
  const pairs = data.pairs
    .filter(p => p && typeof p.letter === 'string' && typeof p.caseType === 'string')
    .map(p => ({ letter: p.letter, caseType: p.caseType }));
  return { status: 'found', pairs };
}

/**
 * Fetches the authoritative set of (letter, caseType) pairs this student
 * has mastered. Never throws — a network/server failure resolves to
 * `read_failed` with an EMPTY pairs list, which filterUnmasteredSequence()
 * below treats as "nothing confirmed mastered yet" (fails open to showing
 * the full sequence rather than silently hiding letters on a transient
 * error — a false "not mastered" is a harmless re-practice, a false
 * "mastered" would wrongly hide a letter the child never actually wrote).
 *
 * @param {number|string} studentId
 * @returns {Promise<ReturnType<typeof normalizeMasteredLettersResponse>>}
 */
export async function fetchMasteredLetters(studentId) {
  try {
    const response = await client.get(ENDPOINTS.MASTERED_LETTERS(studentId));
    return normalizeMasteredLettersResponse(response?.data);
  } catch (err) {
    if (typeof __DEV__ !== 'undefined' && __DEV__) {
      console.log('[masteredLetterFiltering] fetch failed — treating as read_failed:', err?.message ?? err);
    }
    return { ...FAILSAFE };
  }
}

/**
 * Removes every entry of `sequence` whose (letter, caseType) appears in
 * `masteredPairs`, preserving the relative order of everything that
 * remains. Pure, synchronous, no I/O.
 *
 * @param {Array<{letter: string, caseType: string}>} sequence — the
 *   adaptive-order array (from generateAdaptiveSequence()/letterCategories.js
 *   entries, or getAllLetters()'s default-order fallback — both share this
 *   {letter, caseType, ...} shape).
 * @param {Array<{letter: string, caseType: string}>} masteredPairs
 * @returns {Array} the filtered sequence — same element objects, new array.
 */
export function filterUnmasteredSequence(sequence, masteredPairs) {
  if (!Array.isArray(sequence)) return [];
  if (!Array.isArray(masteredPairs) || masteredPairs.length === 0) return [...sequence];

  const masteredSet = new Set(masteredPairs.map(p => pairKey(p.letter, p.caseType)));
  return sequence.filter(entry => !masteredSet.has(pairKey(entry?.letter, entry?.caseType)));
}
